### ISSUE TITLE
--silent has to mute Warnings

### ISSUE THREAD

**Issue by bykof** [tabulapdf/tabula-java#115]
If I use tabula in the console, I get sometimes warnings. Everything works fine (I get all my data), so I want to mute the warnings and use --silent. I expected that it would mute the warnings as well but it doesn't.

Here is an example output:
`Okt 25, 2016 1:00:13 PM org.apache.pdfbox.util.PDFStreamEngine processOperator
WARNUNG: java.lang.ArrayIndexOutOfBoundsException: 10
java.lang.ArrayIndexOutOfBoundsException: 10
        at java.awt.geom.Path2D$Float$TxIterator.currentSegment(Path2D.java:1029)
        at technology.tabula.ObjectExtractor.strokeOrFillPath(ObjectExtractor.java:226)
        at technology.tabula.ObjectExtractor.strokePath(ObjectExtractor.java:275)
        at org.apache.pdfbox.util.operator.pagedrawer.StrokePath.process(StrokePath.java:47)
        at org.apache.pdfbox.util.PDFStreamEngine.processOperator(PDFStreamEngine.java:562)
        at org.apache.pdfbox.util.PDFStreamEngine.processOperator(PDFStreamEngine.java:537)
        at org.apache.pdfbox.util.operator.pagedrawer.FillNonZeroAndStrokePath.process(FillNonZeroAndStrokePath.java:52)
        at org.apache.pdfbox.util.PDFStreamEngine.processOperator(PDFStreamEngine.java:562)
        at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:269)
        at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:236)
        at org.apache.pdfbox.util.PDFStreamEngine.processStream(PDFStreamEngine.java:216)
        at technology.tabula.ObjectExtractor.drawPage(ObjectExtractor.java:153)
        at technology.tabula.ObjectExtractor.extractPage(ObjectExtractor.java:108)
        at technology.tabula.PageIterator.next(PageIterator.java:29)
        at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:144)
        at technology.tabula.CommandLineApp.main(CommandLineApp.java:60)
`

**Comment by pungoyal** [comment]
have a look at https://github.com/tabulapdf/tabula-java/issues/231
