### ISSUE TITLE
WARNING: java.lang.ArrayIndexOutOfBoundsException: 80

### ISSUE THREAD

**Issue by malaterre** [tabulapdf/tabula-java#124]
For some reason tabula does not like my PDF. Steps:

```
$ wget https://www.brainlab.com/wp-content/uploads/2014/01/dicom-iplan-rt-dose-30.pdf
$ java -jar $TABULA -p 23 dicom-iplan-rt-dose-30.pdf
Nov 25, 2016 1:16:53 PM org.apache.pdfbox.util.operator.pagedrawer.FillEvenOddRule process
WARNING: java.lang.ArrayIndexOutOfBoundsException: 80
java.lang.ArrayIndexOutOfBoundsException: 80
	at java.awt.geom.Path2D$Float$TxIterator.currentSegment(Path2D.java:956)
	at technology.tabula.ObjectExtractor.strokeOrFillPath(ObjectExtractor.java:226)
	at technology.tabula.ObjectExtractor.fillPath(ObjectExtractor.java:285)
	at org.apache.pdfbox.util.operator.pagedrawer.FillEvenOddRule.process(FillEvenOddRule.java:57)
	at org.apache.pdfbox.util.PDFStreamEngine.processOperator(PDFStreamEngine.java:562)
	at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:269)
	at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:236)
	at org.apache.pdfbox.util.PDFStreamEngine.processStream(PDFStreamEngine.java:216)
	at technology.tabula.ObjectExtractor.drawPage(ObjectExtractor.java:153)
	at technology.tabula.ObjectExtractor.extractPage(ObjectExtractor.java:108)
	at technology.tabula.PageIterator.next(PageIterator.java:29)
	at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:144)
	at technology.tabula.CommandLineApp.main(CommandLineApp.java:60)

Nov 25, 2016 1:16:53 PM org.apache.pdfbox.util.PDFStreamEngine processOperator
WARNING: java.lang.ArrayIndexOutOfBoundsException: 160
java.lang.ArrayIndexOutOfBoundsException: 160
	at java.awt.geom.Path2D$Float$TxIterator.currentSegment(Path2D.java:956)
	at technology.tabula.ObjectExtractor.strokeOrFillPath(ObjectExtractor.java:226)
	at technology.tabula.ObjectExtractor.strokePath(ObjectExtractor.java:275)
	at org.apache.pdfbox.util.operator.pagedrawer.StrokePath.process(StrokePath.java:47)
	at org.apache.pdfbox.util.PDFStreamEngine.processOperator(PDFStreamEngine.java:562)
	at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:269)
	at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:236)
	at org.apache.pdfbox.util.PDFStreamEngine.processStream(PDFStreamEngine.java:216)
	at technology.tabula.ObjectExtractor.drawPage(ObjectExtractor.java:153)
	at technology.tabula.ObjectExtractor.extractPage(ObjectExtractor.java:108)
	at technology.tabula.PageIterator.next(PageIterator.java:29)
	at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:144)
	at technology.tabula.CommandLineApp.main(CommandLineApp.java:60)
[...]
```

The output seems to be generated, but if this warning should be accepted, I think it should be hidden.

**Comment by arturgspb** [comment]
I catch this error when run program on ubuntu server, on desktop it work normally

**Comment by goretkin** [comment]
I get a similar error on this pdf: http://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1001878 (DOI:10.1371/journal.pmed.1001878)

```
Jul 19, 2017 11:49:42 AM org.apache.pdfbox.util.PDFStreamEngine processOperator
WARNING: java.lang.ArrayIndexOutOfBoundsException: 4
java.lang.ArrayIndexOutOfBoundsException: 4
	at java.awt.geom.Path2D$Float$TxIterator.currentSegment(Path2D.java:1029)
	at technology.tabula.ObjectExtractor.strokeOrFillPath(ObjectExtractor.java:226)
	at technology.tabula.ObjectExtractor.strokePath(ObjectExtractor.java:275)
	at org.apache.pdfbox.util.operator.pagedrawer.StrokePath.process(StrokePath.java:47)
	at org.apache.pdfbox.util.PDFStreamEngine.processOperator(PDFStreamEngine.java:562)
	at org.apache.pdfbox.util.PDFStreamEngine.processOperator(PDFStreamEngine.java:537)
	at org.apache.pdfbox.util.operator.pagedrawer.FillEvenOddAndStrokePath.process(FillEvenOddAndStrokePath.java:52)
	at org.apache.pdfbox.util.PDFStreamEngine.processOperator(PDFStreamEngine.java:562)
	at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:269)
	at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:236)
	at org.apache.pdfbox.util.PDFStreamEngine.processStream(PDFStreamEngine.java:216)
	at technology.tabula.ObjectExtractor.drawPage(ObjectExtractor.java:153)
	at technology.tabula.ObjectExtractor.extractPage(ObjectExtractor.java:108)
	at technology.tabula.PageIterator.next(PageIterator.java:29)
	at technology.tabula.CommandLineApp.extractFile(CommandLineApp.java:160)
	at technology.tabula.CommandLineApp.extractFileTables(CommandLineApp.java:123)
	at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:104)
	at technology.tabula.CommandLineApp.main(CommandLineApp.java:74)
```

version info:
```
n$ java -jar tabula-0.9.2-jar-with-dependencies.jar   -v
tabula 0.9.1 (c) 2012-2016 Manuel Aristarán
```

**Comment by jazzido** [comment]
Thanks @goretkin. We need to address that warning, but it can be safely ignored.

Also, can you share the command line parameters that you used to process document?

**Comment by goretkin** [comment]
@jazzido Thanks for the information. I had assumed that those warnings were perhaps swallowing up some information from the table.

I edited my first post to show the command I ran to produce those warnings.
