### ISSUE TITLE
Exception in thread "main" - multiple errors resulting in blank output

### ISSUE THREAD

**Issue by klynched** [tabulapdf/tabula-java#138]
When I use the Tabula GUI I can extract fine from PDFs, but when I use the same coordinates and script it I get the java errors below.

Exception in thread "main" java.lang.NoSuchMethodError: java.lang.Integer.compare(II)I
	at technology.tabula.TextChunk.isLtrDominant(TextChunk.java:179)
	at technology.tabula.TextElement.mergeWords(TextElement.java:271)
	at technology.tabula.TextElement.mergeWords(TextElement.java:105)
	at technology.tabula.extractors.SpreadsheetExtractionAlgorithm.extract(SpreadsheetExtractionAlgorithm.java:118)
	at technology.tabula.extractors.SpreadsheetExtractionAlgorithm.extract(SpreadsheetExtractionAlgorithm.java:86)
	at technology.tabula.extractors.SpreadsheetExtractionAlgorithm.isTabular(SpreadsheetExtractionAlgorithm.java:159)
	at technology.tabula.CommandLineApp$TableExtractor.extractTables(CommandLineApp.java:353)
	at technology.tabula.CommandLineApp.extractFile(CommandLineApp.java:166)
	at technology.tabula.CommandLineApp.extractFileInto(CommandLineApp.java:138)
	at technology.tabula.CommandLineApp.extractFileTables(CommandLineApp.java:128)
	at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:104)
	at technology.tabula.CommandLineApp.main(CommandLineApp.java:74)

**Comment by jeremybmerrill** [comment]
1.) can you share the PDF that's causing this problem?
2.) can you check which Java version you're using? ( run `java -version`) If you're using Java 1.6, please upgrade to 1.7 or greater.
