### ISSUE TITLE
pdfbox error, pixelmap has no data

### ISSUE THREAD

**Issue by AnniePW** [tabulapdf/tabula-java#152]
Attempting to parse a 250 pg pdf spreadsheet and keep getting errors related to pdfbox. Not sure if this is related to settings on my pc or related to the recent pdfbox update you guys did (I see you updated pdfbox ~5 hours ago). 

I attempted only parsing one page and changing the area, but I still got the same errors. 

Any help on this would be appreciated!

Code:`java -jar tab/tabula-0.9.2-jar-with-dependencies.jar -p 1 -a 33.94,30.7,1008.95,1588.36 -o file.csv file.pdf `

Error:
`Mar 27, 2017 2:57:29 PM org.apache.pdfbox.pdfparser.XrefTrailerResolver setStartxref
WARNING: Did not found XRef object pointed to by 'Prev' key at position 2920626
Mar 27, 2017 2:57:31 PM org.apache.pdfbox.filter.JBIG2Filter decode
SEVERE: Can't find an ImageIO plugin to decode the JBIG2 encoded datastream.
Mar 27, 2017 2:57:31 PM org.apache.pdfbox.pdmodel.graphics.xobject.PDPixelMap getRGBImage
SEVERE: Something went wrong ... the pixelmap doesn't contain any data.
Mar 27, 2017 2:57:31 PM org.apache.pdfbox.util.operator.pagedrawer.Invoke process
WARNING: getRGBImage returned NULL
Exception in thread "main" java.lang.NoSuchMethodError: java.lang.Integer.compare(II)I
	at technology.tabula.TextChunk.isLtrDominant(TextChunk.java:179)
	at technology.tabula.TextElement.mergeWords(TextElement.java:271)
	at technology.tabula.TextElement.mergeWords(TextElement.java:105)
	at technology.tabula.extractors.BasicExtractionAlgorithm.extract(BasicExtractionAlgorithm.java:46)
	at technology.tabula.CommandLineApp$TableExtractor.extractTablesBasic(CommandLineApp.java:385)
	at technology.tabula.CommandLineApp$TableExtractor.extractTables(CommandLineApp.java:359)
	at technology.tabula.CommandLineApp.extractFile(CommandLineApp.java:166)
	at technology.tabula.CommandLineApp.extractFileInto(CommandLineApp.java:138)
	at technology.tabula.CommandLineApp.extractFileTables(CommandLineApp.java:128)
	at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:104)
	at technology.tabula.CommandLineApp.main(CommandLineApp.java:74)
`

**Comment by jazzido** [comment]
Hi @AnniePW, thanks for your report.

Looks like this is related, or is a duplicate of #102. I'd be happy to take a look to the file that you're trying to process. If it can't be shared publicly, feel free to email it to me directly: *manuel at jazzido dot com*.

**Comment by AnniePW** [comment]
Thanks so much @jazzido! Will email you.
