### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by James-OHara** [tabulapdf/tabula-java#198]
Processing this PDF works with Tabula web, but not tabula-java where it returns NullPointerException with traceback below (using script from Tabula web). Unfortunately can't share the actual pdf file. 

java -jar tabula-java.jar -a 27.72,26.235,554.4,439.065 -l -g -p 1 [filename.pdf]
Exception in thread "main" java.lang.NullPointerException
        at technology.tabula.ObjectExtractorStreamEngine$PointComparator.compare(ObjectExtractorStreamEngine.java:258)
        at technology.tabula.ObjectExtractorStreamEngine.strokeOrFillPath(ObjectExtractorStreamEngine.java:219)
        at technology.tabula.ObjectExtractorStreamEngine.strokePath(ObjectExtractorStreamEngine.java:140)
        at org.apache.pdfbox.contentstream.operator.graphics.StrokePath.process(StrokePath.java:36)
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:838)
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:819)
        at org.apache.pdfbox.contentstream.operator.graphics.CloseAndStrokePath.process(CloseAndStrokePath.java:37)
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:838)
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:495)
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:469)
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:150)
        at technology.tabula.ObjectExtractor.extractPage(ObjectExtractor.java:26)
        at technology.tabula.PageIterator.next(PageIterator.java:29)
        at technology.tabula.CommandLineApp.extractFile(CommandLineApp.java:157)
        at technology.tabula.CommandLineApp.extractFileTables(CommandLineApp.java:120)
        at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:101)
        at technology.tabula.CommandLineApp.main(CommandLineApp.java:71)

Also doesn't work using stream, without specifying the area or on any of the other pages.

**Comment by zt-nirav** [comment]
Even I'm facing the same issue. Here is a sample PDF for which the issue reproduces. 
[LeggMason_Prospectus_.pdf](https://github.com/tabulapdf/tabula-java/files/1526868/LeggMason_Prospectus_.pdf)


Would be great, if we can get any help on this.

**Comment by prashantrajpal** [comment]
https://github.com/tabulapdf/tabula-java/blob/4e15a5034e27099d20b2d509d0e5b5a1cda2e557/src/main/java/technology/tabula/ObjectExtractorStreamEngine.java#L219

This line here is causing this issue....."end_pos" is set to null initially and not modified...I am facing this issue too.

**Comment by tgarcia-justice** [comment]
I experienced the same issue. I was able to work around it by using tabula v0.9.2. It still produced this error message, but at least my files were extracted,
