### ISSUE TITLE
lines must be orthogonal, vertical and horizontal exception

### ISSUE THREAD

**Issue by paulpeeling** [tabulapdf/tabula-java#218]
Looping through the pages of a [PDF](https://www.bankofengland.co.uk/-/media/boe/files/inflation-report/2018/february/inflation-report-february-2018.pdf), this exception was thrown by the SpreadsheetExtractionAlgorithm. There isn't a table on this page that should be extracted.

`
$ java -jar tabula-1.0.1-jar-with-dependencies.jar -page 17 -r inflation-report-february-2018.pdf
Exception in thread "main" java.lang.IllegalArgumentException: lines must be orthogonal, vertical and horizontal
        at technology.tabula.Ruling.intersectionPoint(Ruling.java:216)
        at technology.tabula.Ruling.findIntersections(Ruling.java:385)
        at technology.tabula.extractors.SpreadsheetExtractionAlgorithm.findCells(SpreadsheetExtractionAlgorithm.java:180)
        at technology.tabula.extractors.SpreadsheetExtractionAlgorithm.extract(SpreadsheetExtractionAlgorithm.java:106)
        at technology.tabula.extractors.SpreadsheetExtractionAlgorithm.extract(SpreadsheetExtractionAlgorithm.java:84)
        at technology.tabula.CommandLineApp$TableExtractor.extractTablesSpreadsheet(CommandLineApp.java:392)
        at technology.tabula.CommandLineApp$TableExtractor.extractTables(CommandLineApp.java:363)
        at technology.tabula.CommandLineApp.extractFile(CommandLineApp.java:163)
        at technology.tabula.CommandLineApp.extractFileTables(CommandLineApp.java:120)
        at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:101)
        at technology.tabula.CommandLineApp.main(CommandLineApp.java:71)
`

**Comment by fl4p** [comment]
Same here, [pdf](https://www.onsemi.com/pdf/datasheet/ntmfs6h800nl-d.pdf)
