### ISSUE TITLE
Parsing behaviour tabula-java vs. tabula-extractor vs. tabula

### ISSUE THREAD

**Issue by davincho** [tabulapdf/tabula-java#26]
Testfile: https://www.dropbox.com/s/6crie7y5gqadwa5/1.pdf?dl=0

Using tabula-extractor (installed via jruby -S gem install tabula-extractor) the extraction result looks like the following:

**Command:** ``tabula 1.pdf --spreadsheet -o tmp.txt``
```text
WOCHENPROGRAMM Tel. 03112/36484
"","","","","","","","",""
Film,Info,"Fr, 04.09","Sa, 05.09","So, 06.09","Mo, 07.09","Di, 08.09","Mi, 09.09","Do, 10.09"
"","","","","","","","",""
"Fack ju Göhte                                                       Doublefeature EHP ab € 13,-",239 min,"","","","","",21:30,""
Fack ju Göhte 2                                                     Vorpremiere,90 min,"","","","","",23:59,""
Ricki and the Flash                                                 Originalversion ohne Untertitel,"ab 6 J., sehensw.                     100 min","","","","",20:00,"",""
"Taxi Teheran                                                        Dieselkino Kult[ur] EHP ab € 7,-",86 min,"","","",19:00,"",19:00,""
Jack,98 min,"","","","","","",20:30
Fack ju Göhte 2,117 min,"","","","","","",16:30 18:00         20:15
Filmfrühstück: French Women - Was Frauen wirklich wollen            Frühstück ab 09:30 Uhr,ab 12 J.                         117 min,"","",11:00,"","","",""
Filmfrühstück: Ricki - Wie Familie so ist                           Frühstück ab 09:30 Uhr,99 min,"","",11:00,"","","",""
Filmfrühstück: The Transporter Refueled                             Frühstück ab 09:30 Uhr,96 min,"","",11:00,"","","",""
French Women - Was Frauen wirklich wollen,ab 12 J.                         117 min,17:30 20:15,17:30 20:15,17:30 20:15,17:30 19:45,17:30 19:45,17:30 19:45,17:30 19:45
Ricki - Wie Familie so ist,"ab 6 J., sehensw.                     100 min",17:00 19:45,17:00 19:45,17:00 20:00,17:00 20:00,18:45,17:00 20:00,17:00 20:00
The Transporter Refueled,96 min,18:15 20:45,18:15 20:45,16:30 18:30         20:30,17:45 20:45,17:45 20:45,17:45 20:45,17:45 20:45
Gallows,ab 16 J.                          81 min,21:00,21:00,21:00,21:00,21:00,19:45,19:00
Hitman: Agent 47,ab 16 J.                          97 min,18:00 20:00         22:00,18:00 20:00         22:00,16:45 18:45         20:45,18:30 20:30,18:30 20:30,18:00 21:00,18:30 21:00
"Der kleine Rabe Socke 2 - Das große Rennen                          EHP € 6,50","jfr., sehensw.                       73 min",16:00,16:00,14:45,15:15,16:00,15:15,15:15
Vacation - Wir sind die Griswolds,ab 12 J.                          99 min,19:00,19:00,19:00,19:00,19:00,19:00,19:00
Margos Spuren,ab 8 J.                          109 min,16:15,16:15,15:30,16:45,16:45,16:45,15:30
"Ooops! Die Arche ist weg 3D                                         EHP € 8,-","ab 6 J., sehensw.                      87 min",15:45,15:45,14:30,15:45,15:45,16:15,15:45
Pixels 3D,ab 6 J.                          101 min,16:45,16:45,15:00,16:00,16:30,16:00,16:15
Minions 3D,"ab 6 J., sehensw.                      91 min",16:30,16:30,14:15 16:00,16:30,16:15,15:45,16:00
Mission: Impossible 5 - Rogue Nation,ab 12 J.                         131 min,20:30,20:30,17:45,20:15,20:15,20:15,""
Dating Queen,ab 12 J.                         122 min,18:15,18:15,15:45,18:00,18:00,18:00,""
Broadway Therapy,93 min,18:45,18:45,18:00,"","","",""
Magic Mike XXL,ab 12 J.                         116 min,21:45,21:45,19:45,"","","",""
```
Using tabula-java (git clone and build via mvn clean compile assembly:single) the extraction fails with a Stackoverflow exception:

**Command:** ``java -jar tabula-extractor-0.7.4-SNAPSHOT-jar-with-dependencies.jar 1.pdf --spreadsheet -o tmp.txt``
```text
Exception in thread "main" java.lang.StackOverflowError
	at technology.tabula.QuickSort.split(QuickSort.java:96)
	at technology.tabula.QuickSort.quicksort(QuickSort.java:72)
	at technology.tabula.QuickSort.quicksort(QuickSort.java:73)
	at technology.tabula.QuickSort.quicksort(QuickSort.java:73)
	at technology.tabula.QuickSort.quicksort(QuickSort.java:73)
	at technology.tabula.QuickSort.quicksort(QuickSort.java:73)
	at technology.tabula.QuickSort.quicksort(QuickSort.java:73)
	at technology.tabula.QuickSort.quicksort(QuickSort.java:73)
        .....
```
Running tabula from source (master branch) - Auto detection of tables (but deselecting the title table)
**Stream**:

```text
"Fack ju Göhte                                                       
Doublefeature EHP ab € 13,-",239 min,,,,,,21:30,
"Fack ju Göhte 2                                                     
Vorpremiere",90 min,,,,,,23:59,
"Ricki and the Flash                                                 
Originalversion ohne Untertitel","ab 6 J., sehensw.        
             100 min",,,,,20:00,,
"Taxi Teheran                                                        
Dieselkino Kult[ur] EHP ab € 7,-",86 min,,,,19:00,,19:00,
Jack,98 min,,,,,,,20:30
Fack ju Göhte 2,117 min,,,,,,,"16:30 18:00         
20:15"
"Filmfrühstück: French Women - Was Frauen wirklich wollen            
Frühstück ab 09:30 Uhr","ab 12 J.            
             117 min",,,11:00,,,,
"Filmfrühstück: Ricki - Wie Familie so ist                           
Frühstück ab 09:30 Uhr",99 min,,,11:00,,,,
"Filmfrühstück: The Transporter Refueled                             
Frühstück ab 09:30 Uhr",96 min,,,11:00,,,,
French Women - Was Frauen wirklich wollen,"ab 12 J.            
             117 min",17:30 20:15,17:30 20:15,17:30 20:15,17:30 19:45,17:30 19:45,17:30 19:45,17:30 19:45
Ricki - Wie Familie so ist,"ab 6 J., sehensw.        
             100 min",17:00 19:45,17:00 19:45,17:00 20:00,17:00 20:00,18:45,17:00 20:00,17:00 20:00
The Transporter Refueled,96 min,18:15 20:45,18:15 20:45,"16:30 18:30         
20:30",17:45 20:45,17:45 20:45,17:45 20:45,17:45 20:45
Gallows,"ab 16 J.            
              81 min",21:00,21:00,21:00,21:00,21:00,19:45,19:00
Hitman: Agent 47,"ab 16 J.            
              97 min","18:00 20:00         
22:00","18:00 20:00         
22:00","16:45 18:45         
20:45",18:30 20:30,18:30 20:30,18:00 21:00,18:30 21:00
"Der kleine Rabe Socke 2 - Das große Rennen                          
EHP € 6,50","jfr., sehensw.         
              73 min",16:00,16:00,14:45,15:15,16:00,15:15,15:15
Vacation - Wir sind die Griswolds,"ab 12 J.            
              99 min",19:00,19:00,19:00,19:00,19:00,19:00,19:00
Margos Spuren,"ab 8 J.             
             109 min",16:15,16:15,15:30,16:45,16:45,16:45,15:30
"Ooops! Die Arche ist weg 3D                                         
EHP € 8,-","ab 6 J., sehensw.        
              87 min",15:45,15:45,14:30,15:45,15:45,16:15,15:45
Pixels 3D,"ab 6 J.             
             101 min",16:45,16:45,15:00,16:00,16:30,16:00,16:15
Minions 3D,"ab 6 J., sehensw.        
              91 min",16:30,16:30,14:15 16:00,16:30,16:15,15:45,16:00
Mission: Impossible 5 - Rogue Nation,"ab 12 J.            
             131 min",20:30,20:30,17:45,20:15,20:15,20:15,
Dating Queen,"ab 12 J.            
             122 min",18:15,18:15,15:45,18:00,18:00,18:00,
Broadway Therapy,93 min,18:45,18:45,18:00,,,,
Magic Mike XXL,"ab 12 J.            
             116 min",21:45,21:45,19:45,,,,
```

**Latice**:
On Preview of Extracted Tabular Data" screen Infinite loading

**Comment by jazzido** [comment]
Thanks, @davincho 

I've started to look into this issue. There's something happening with the sorting algorithm we use. Forcing the use of java's builtin sorting method, seems to help:

```
java -Djava.util.Arrays.useLegacyMergeSort=true -jar ./target/tabula-extractor-0.7.4-SNAPSHOT-jar-with-dependencies.jar -p 1 --spreadsheet 1.pdf
```

I'll update this issue when I have the chance to dig deeper.

**Comment by davincho** [comment]
@jazzido using the additional parameter ``-Djava.util.Arrays.useLegacyMergeSort=true`` still leads to a ``StackOverflowError``.

**Comment by jazzido** [comment]
The bug can be also triggered in PDFBox alone. Just reported the issue: https://issues.apache.org/jira/browse/PDFBOX-2996

**Comment by THausherr** [comment]
Try java option  -Xss2m (that one worked on PDBox)

**Comment by jazzido** [comment]
Thanks @THausherr. It worked with that stack size.

**Comment by jazzido** [comment]
@davincho, this should be now fixed in `HEAD` thanks to @melisabok's contribution (#32)

@THausherr, we will port this to PDFBox and submit a patch soon.
