### ISSUE TITLE
Two test failures

### ISSUE THREAD

**Issue by yurivict** [tabulapdf/tabula-java#27]
I am getting two failures with version 6a13b03:

```
AMBURI,"HUGO ALBERTO ",14.096.560,20-14096560-0,09/10/2013,EFECTIVO,"$ 20.000,00"^M
BERRA,"CLAUDIA SUSANA ",14.433.112,27-14433112-0,09/10/2013,EFECTIVO,"$ 10.000,00"^M
Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.787 sec <<< FAILURE!
testExtractColumnsCorrectly3(technology.tabula.TestBasicExtractor)  Time elapsed: 0.137 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<AARON [, JOSHUA, N]> but was:<AARON [JOSHUA N , ,]>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at technology.tabula.UtilsForTesting.assertTableEquals(UtilsForTesting.java:41)
```

```
INFO: unsupported/disabled operation: EMC
Tests run: 17, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.183 sec <<< FAILURE!
testSpreadsheetWithNoBoundingFrameShouldBeSpreadsheet(technology.tabula.TestSpreadsheetExtractor)  Time elapsed: 0.245 sec  <<< FAILURE!
java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
```

I never built it before. Observed errors on FreeBSD, while trying to make a package.

**Comment by jazzido** [comment]
Thanks for the report, @yurivict 

Those errors are expected, I should mark them as failing or something.

**Comment by melisabok** [comment]
@jazzido I think there is no test failing now.
