### ISSUE TITLE
Serveral pdfs raise Exception in thread "main" java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by erdelmaero** [tabulapdf/tabula-java#396]
In serveral PDFs I tried to use tabula-java on, I get this execption.

```
java -jar tabula-1.0.4-jar-with-dependencies.jar --area "166.972,19.338,280.766,556.325" --format JSON "./filename.pdf" 
Exception in thread "main" java.lang.UnsupportedOperationException
        at technology.tabula.Ruling.setEnd(Ruling.java:112)
        at technology.tabula.Ruling.expand(Ruling.java:197)
        at technology.tabula.Ruling.nearlyIntersects(Ruling.java:172)
        at technology.tabula.Ruling.collapseOrientedRulings(Ruling.java:425)
        at technology.tabula.Ruling.collapseOrientedRulings(Ruling.java:409)
        at technology.tabula.Page.getRulings(Page.java:181)
        at technology.tabula.Page.getArea(Page.java:80)
        at technology.tabula.CommandLineApp.extractFile(CommandLineApp.java:182)
        at technology.tabula.CommandLineApp.extractFileTables(CommandLineApp.java:129)
        at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:111)
        at technology.tabula.CommandLineApp.main(CommandLineApp.java:81)
```
Do you have any advice? I'll try to get permission to publish an example file.

**Comment by sengerts** [comment]
I am having the same issue. Are there any news on it?
