### ISSUE TITLE
Ruby Initialization Failed

### ISSUE THREAD

**Issue by Fradinho** [tabulapdf/tabula-java#404]
From CMD:
`2021-01-20 12:30:42.672:INFO::main: Logging initialized @2273ms
2021-01-20 12:30:42.672:INFO:oejr.Runner:main: Runner
2021-01-20 12:30:43.173:INFO:oejs.Server:main: jetty-9.2.9.v20150224
2021-01-20 12:30:56.862:WARN:oeja.AnnotationConfiguration:main: ServletContainerInitializers: detected. Class hierarchy: empty
INFO: jruby 9.1.15.0 (2.3.3) 2017-12-07 929fde8 Java HotSpot(TM) Client VM 25.281-b09 on 1.8.0_281-b09 +jit [mswin32-x86]
INFO: using a shared (threadsafe!) runtime
An exception happened during JRuby-Rack startup
no such file to load -- bundler/shared_helpers
--- System
jruby 9.1.15.0 (2.3.3) 2017-12-07 929fde8 Java HotSpot(TM) Client VM 25.281-b09 on 1.8.0_281-b09 +jit [mswin32-x86]
Time: 2021-01-20 12:31:04 +0000
Server: jetty/9.2.9.v20150224
jruby.home: uri:classloader://META-INF/jruby.home

--- Context Init Parameters:
jruby.compat.version = 1.9
jruby.rack.logging = stderr
public.root = /
rack.env = production

--- Backtrace
LoadError: no such file to load -- bundler/shared_helpers
require at org/jruby/RubyKernel.java:955
require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
at file:/C:/Users/Andr%C3%A9/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-5367519194782960156.dir/webapp/META-INF/init.rb:29
eval at org/jruby/RubyKernel.java:994
block in load_settings_from_init_rb at uri:classloader:/jruby/rack/booter.rb:256
each at org/jruby/RubyArray.java:1735
load_settings_from_init_rb at uri:classloader:/jruby/rack/booter.rb:243
boot! at uri:classloader:/jruby/rack/booter.rb:99
at uri:classloader:/jruby/rack/boot/rack.rb:10
load at org/jruby/RubyKernel.java:973
at <script>:1
--- RubyGems
Gem.dir: C:/Users/AndrÚ/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar--any-5367519194782960156.dir/webapp/WEB-INF/gems
Gem.path:
C:/Users/AndrÚ/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar--any-5367519194782960156.dir/webapp/WEB-INF/gems
Activated gems:
did_you_mean-1.0.1

--- Bundler
undefined method `bundle_path' for Bundler:Module

--- JRuby-Rack Config
compat_version = RUBY1_9
default_logger = org.jruby.rack.logging.StandardOutLogger@1a256d
equals = <error: >
err = java.io.PrintStream@164eed1
filter_adds_html = true
filter_verifies_resource = false
ignore_environment = false
initial_memory_buffer_size =
initial_runtimes =
jms_connection_factory =
jms_jndi_properties =
logger = org.jruby.rack.logging.OutputStreamLogger@4e8c9d
logger_class_name = stderr
logger_name = jruby.rack
maximum_memory_buffer_size =
maximum_runtimes =
num_initializer_threads =
out = java.io.PrintStream@1973858
rackup =
rackup_path =
rewindable = true
runtime_arguments =
runtime_environment =
runtime_timeout_seconds =
serial_initialization = false
servlet_context = ServletContext@o.e.j.w.WebAppContext@18cccef{/,file:/C:/Users/Andr%C3%A9/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-5367519194782960156.dir/webapp/,STARTING}{file:/C:/Users/Andr%C3%A9/Desktop/tabula/tabula.jar}
throw_init_exception = false

--- $LOAD_PATH:
C:\Users\Andr├®\AppData\Local\Temp\jetty-0.0.0.0-8080-tabula.jar--any-5367519194782960156.dir\webapp\WEB-IN
uri:classloader:/META-INF/jruby.home/lib/ruby/2.3/site_ruby
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib
ERROR: initialization failed
org.jruby.rack.RackInitializationException: no such file to load -- bundler/shared_helpers
from org/jruby/RubyKernel.java:955:in require' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55:in require'
from file:/C:/Users/Andr%C3%A9/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar--any-5367519194782960156.dir/webapp/META-INF/init.rb:29:in <eval>' from org/jruby/RubyKernel.java:994:in eval'
from uri:classloader:/jruby/rack/booter.rb:256:in block in load_settings_from_init_rb' from org/jruby/RubyArray.java:1735:in each'
from uri:classloader:/jruby/rack/booter.rb:243:in load_settings_from_init_rb' from uri:classloader:/jruby/rack/booter.rb:99:in boot!'
from uri:classloader:/jruby/rack/boot/rack.rb:10:in <main>' from org/jruby/RubyKernel.java:973:in load'
from <script>:1:in `

'
    at org.jruby.rack.RackInitializationException.wrap(RackInitializationException.java:29)
    at org.jruby.rack.RackApplicationFactoryDecorator.init(RackApplicationFactoryDecorator.java:104)
    at org.jruby.rack.RackServletContextListener.contextInitialized(RackServletContextListener.java:50)
    at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
    at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
    at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
    at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
    at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:163)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.server.Server.start(Server.java:387)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    at org.eclipse.jetty.server.Server.doStart(Server.java:354)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.runner.Runner.run(Runner.java:509)
    at org.eclipse.jetty.runner.Runner.main(Runner.java:557)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at WarMain.launchWebServer(WarMain.java:187)
    at WarMain.start(WarMain.java:345)
    at JarMain.doStart(JarMain.java:233)
    at WarMain.main(WarMain.java:367)
Caused by: org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- bundler/shared_helpers
at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
at RUBY.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)
at RUBY.(file:/C:/Users/Andr%C3%A9/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar--any-5367519194782960156.dir/webapp/META-INF/init.rb:29)
at org.jruby.RubyKernel.eval(org/jruby/RubyKernel.java:994)
at RUBY.block in load_settings_from_init_rb(uri:classloader:/jruby/rack/booter.rb:256)
at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1735)
at RUBY.load_settings_from_init_rb(uri:classloader:/jruby/rack/booter.rb:243)
at RUBY.boot!(uri:classloader:/jruby/rack/booter.rb:99)
at RUBY.

(uri:classloader:/jruby/rack/boot/rack.rb:10)
at org.jruby.RubyKernel.load(org/jruby/RubyKernel.java:973)
at RUBY.(<script>:1)
2021-01-20 12:31:04.524:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@18cccef{/,file:/C:/Users/Andr%C3%A9/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar--any-5367519194782960156.dir/webapp/,AVAILABLE}{file:/C:/Users/Andr%C3%A9/Desktop/tabula/tabula.jar}
2021-01-20 12:31:04.524:WARN:oejsh.RequestLogHandler:main: !RequestLog
2021-01-20 12:31:04.571:INFO:oejs.ServerConnector:main: Started ServerConnector@9453f4{HTTP/1.1}{0.0.0.0:8080}
2021-01-20 12:31:04.571:INFO:oejs.Server:main: Started @24196ms
DEBUG: due a previous initialization failure application instance can not be returned
DEBUG: resetting rack response due exception
WARN: error application could not be initialized
org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- bundler/shared_helpers
at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
at RUBY.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)
at RUBY.(file:/C:/Users/Andr%C3%A9/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-5367519194782960156.dir/webapp/META-INF/init.rb:29)
at org.jruby.RubyKernel.eval(org/jruby/RubyKernel.java:994)
at RUBY.block in load_settings_from_init_rb(uri:classloader:/jruby/rack/booter.rb:256)
at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1735)
at RUBY.load_settings_from_init_rb(uri:classloader:/jruby/rack/booter.rb:243)
at RUBY.boot!(uri:classloader:/jruby/rack/booter.rb:99)
at RUBY.(uri:classloader:/jruby/rack/boot/rack.rb:10)
at org.jruby.RubyKernel.load(org/jruby/RubyKernel.java:973)
at RUBY.(<script>:1)
DEBUG: due a previous initialization failure application instance can not be returned
DEBUG: resetting rack response due exception`
From the browser
org.jruby.rack.RackInitializationException: no such file to load -- bundler/shared_helpers from org/jruby/RubyKernel.java:955:in require'
from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55:in require' from file:/C:/Users/Andr%C3%A9/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-5367519194782960156.dir/webapp/META-INF/init.rb:29:in '
from org/jruby/RubyKernel.java:994:in eval' from uri:classloader:/jruby/rack/booter.rb:256:in block in load_settings_from_init_rb'
from org/jruby/RubyArray.java:1735:in each' from uri:classloader:/jruby/rack/booter.rb:243:in load_settings_from_init_rb'
from uri:classloader:/jruby/rack/booter.rb:99:in boot!' from uri:classloader:/jruby/rack/boot/rack.rb:10:in

'
from org/jruby/RubyKernel.java:973:in load' from <script>:1:in '
at org.jruby.rack.RackInitializationException.wrap(RackInitializationException.java:29)
at org.jruby.rack.RackApplicationFactoryDecorator.init(RackApplicationFactoryDecorator.java:104)
at org.jruby.rack.RackServletContextListener.contextInitialized(RackServletContextListener.java:50)
at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:163)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
at org.eclipse.jetty.server.Server.start(Server.java:387)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
at org.eclipse.jetty.server.Server.doStart(Server.java:354)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at org.eclipse.jetty.runner.Runner.run(Runner.java:509)
at org.eclipse.jetty.runner.Runner.main(Runner.java:557)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at WarMain.launchWebServer(WarMain.java:187)
at WarMain.start(WarMain.java:345)
at JarMain.doStart(JarMain.java:233)
at WarMain.main(WarMain.java:367)
Caused by: org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- bundler/shared_helpers
at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
at RUBY.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)
at RUBY.(file:/C:/Users/Andr%C3%A9/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-5367519194782960156.dir/webapp/META-INF/init.rb:29)
at org.jruby.RubyKernel.eval(org/jruby/RubyKernel.java:994)
at RUBY.block in load_settings_from_init_rb(uri:classloader:/jruby/rack/booter.rb:256)
at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1735)
at RUBY.load_settings_from_init_rb(uri:classloader:/jruby/rack/booter.rb:243)
at RUBY.boot!(uri:classloader:/jruby/rack/booter.rb:99)
at RUBY.

(uri:classloader:/jruby/rack/boot/rack.rb:10)
at org.jruby.RubyKernel.load(org/jruby/RubyKernel.java:973)
at RUBY.(<script>:1)
`

**Comment by abhijit86k** [comment]
Was able to solve this by complete uninstallation
`apt-get sudo apt-get purge openjdk-*`  then with ruby and ruby-dev;
then re-installed openjdk-jre-11:
`sudo apt-get install openjdk-11-jre`

**Comment by m-jahn** [comment]
this worked for me too.

**Comment by vitorialucena** [comment]
> Was able to solve this by complete uninstallation `apt-get sudo apt-get purge openjdk-*` then uninstalling/purging ruby and ruby-dev; then re-installed openjdk-jre-11: `sudo apt-get install openjdk-11-jre`

where do I use these commands tho? I tried on CMD but "apt-get" is not recognized. the same error is appearing to me as I try to install tabula.exe from tabula.technology
