### ISSUE TITLE
tabula command doesn't return the guessed bounding box

### ISSUE THREAD

**Issue by FabriceSalvaire** [tabulapdf/tabula-java#504]
tabula command doesn't return the guessed bounding box, thus py-tabula cannot have this information.

**Comment by morey215** [comment]
Tabula me indica el siguiente error 

Error from tabula-java:


Traceback (most recent call last):
  File "/home/hogar/Escritorio/jupiterr/Pdf_excel/practica.py", line 16, in <module>
    df_list = tabula.read_pdf(archivo_pdf,  pages='all', stream=True)
  File "/opt/odoo16/venv/lib/python3.8/site-packages/tabula/io.py", line 322, in read_pdf
    output = _run(java_options, kwargs, path, encoding)
  File "/opt/odoo16/venv/lib/python3.8/site-packages/tabula/io.py", line 80, in _run
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['java', '-Dfile.encoding=UTF8', '-jar', '/opt/odoo16/venv/lib/python3.8/site-packages/tabula/tabula-1.0.5-jar-with-dependencies.jar', '--pages', 'all', '--stream', '--guess', '--format', 'JSON', '/home/hogar/Escritorio/jupiterr/Pdf_excel/prueba.pdf']' returned non-zero exit status 1.
