### ISSUE TITLE
Algunas dudas.

### ISSUE THREAD

**Issue by aosi87** [tabulapdf/tabula-java#6]
Hola, disculpa que los tenga olvidados, sin embargo he estado algo atareado con otros proyectos, en este fin de semana (MARATONICO) me decidí probar la implementan y sinergia con mi proyecto, y note lo siguiente

1.- Como puedo decirle en linea de comando que use como método de extracción la decisión, ya que en el HOW TO, y README, solo aparecen los métodos **"Hoja de calculo", y "Basico". (Opciones -r, -n)**, pero entonces para que tenemos la opción **--guess ó -g** ya que se utilizaría solo en el caso de seleccionar el método básico.

2.- Otro detalle estoy recibiendo apuntadores nulos al leer este documento [PDF](http://mega.co.nz/#!bJ0gDYQL!U3S1C_skbRmjOL8tA3Il-HDX4VU8TEWarFMPyt4GTuk) y me da estos errores y se ciclan ya que entiende que hay mas paginas en el documento, pero no puede obtenerlas(eso imagino).

```
nov 10, 2014 5:39:54 AM org.apache.pdfbox.util.PDFStreamEngine processOperator
INFORMACIÓN: unsupported/disabled operation: BDC
nov 10, 2014 5:39:59 AM org.apache.pdfbox.util.PDFStreamEngine processOperator
INFORMACIÓN: unsupported/disabled operation: EMC
nov 10, 2014 5:43:35 AM org.apache.pdfbox.util.PDFStreamEngine processOperator
ADVERTENCIA: java.lang.NullPointerException
java.lang.NullPointerException
    at org.nerdpower.tabula.ObjectExtractor$PointComparator.compare(ObjectExtractor.java:36)
    at org.nerdpower.tabula.ObjectExtractor.strokeOrFillPath(ObjectExtractor.java:249)
    at org.nerdpower.tabula.ObjectExtractor.strokePath(ObjectExtractor.java:270)
    at org.apache.pdfbox.util.operator.pagedrawer.StrokePath.process(StrokePath.java:47)
    at org.apache.pdfbox.util.PDFStreamEngine.processOperator(PDFStreamEngine.java:557)
    at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:268)
    at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:235)
    at org.apache.pdfbox.util.PDFStreamEngine.processStream(PDFStreamEngine.java:215)
    at org.nerdpower.tabula.ObjectExtractor.drawPage(ObjectExtractor.java:149)
    at org.nerdpower.tabula.ObjectExtractor.extractPage(ObjectExtractor.java:108)
    at org.nerdpower.tabula.PageIterator.next(PageIterator.java:29)
    at controller.Tabula.extractTables(Tabula.java:153)
    at controller.Tabula.<init>(Tabula.java:76)
    at controller.Tabula.main(Tabula.java:361)
```

Lo anterior ocurre en la siguientes lineas de código:

``` java
PageIterator pageIterator = pages == null ? oe.extract() : oe.extract(pages);
            Page page;
            List<Table> tables = new ArrayList<Table>();

            **while (pageIterator.hasNext()) {**
                page = pageIterator.next();

                if (area != null) {
                    page = page.getArea(area);
                }

                if (method == ExtractionMethod.DECIDE) {
                    method = spreadsheetExtractor.isTabular(page) ? ExtractionMethod.SPREADSHEET : ExtractionMethod.BASIC;
                }
```

Como no soy experto, y con este proyecto es la primera vez que sufro con PDFs, no logro entender por que me retorna null si el PDF contiene paginas y datos.

3.- Ya para finalizar, como puedo interceptar la lectura de datos, es decir entiendo que la variable o arreglo de tablas se llena al extraer por pagina.`tables.addAll(spreadsheetExtractor.extract(page));` pero al momento de trabajar con la lista de tablas no comprendo la estructura de datos dentro de ella, es decir salio como tabla, como una lista, por fila etc. y pues con la falta de documentación si se me ha complicado un poco seguirte el paso. 

De antemano muchas gracias y saludos, espero no importunarte.

Éxito.

**Comment by aosi87** [comment]
Muchas gracias por tu esfuerzo, ahora le hecho un vistazo y practico el uso de tu Debug en el proceso, otra cosa, no se si tengas considerado que hay mas de una tabla por pagina, esto lo pregunto por que me he topado con varios casos de que las tablas están separadas con nombres de tabla antes de sus cabeceras, y si es algo difícil localizarlos con solo espacios vacíos ya que puede dar el caso que en una tabla no tenga mas que una columna o dos cuando mucho. Existe alguna variable o método que me permita retornar o verificar si pertenece a una tabla ese elemento?, de no ser así tenias considerado estos casos? esto lo pregunto para que implemente algo en mi proyecto aparte.


Saludos. =)

**Comment by jazzido** [comment]
Hola,

De momento, los algoritmos implementados en Tabula actuan sobre una área de manera global. Es decir que es reponsabilidad del programador de identificar el área de la tabla que se desea extraer.

Ese es el propósito del parámetro `-a` en el ejecutable que viene con Tabula, que a su vez usa el método `getArea()` de la clase `Page`. Una vez que tienes un objeto `Page`, debes extraer la área que necesitas con `getArea` y pasárselo al `ExtractionAlgorithm` que quieras usar.

Saludos,

M
