### ISSUE TITLE
java.lang.IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by ericevenchick** [tabulapdf/tabula-java#81]
Hello,

This PDF ([toronto-signal4.pdf](https://github.com/tabulapdf/tabula-java/files/259612/toronto-signal4.pdf))  when run with no arguments leads to the following error.

`java -jar ~/Downloads/tabula-0.9.0-SNAPSHOT-jar-with-dependencies.jar --spreadsheet ../inputs/toronto-signal4.pdf
`
`
Exception in thread "main" java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:899)
	at java.util.TimSort.mergeAt(TimSort.java:516)
	at java.util.TimSort.mergeCollapse(TimSort.java:439)
	at java.util.TimSort.sort(TimSort.java:245)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at technology.tabula.Ruling.collapseOrientedRulings(Ruling.java:402)
	at technology.tabula.Ruling.collapseOrientedRulings(Ruling.java:394)
	at technology.tabula.Page.getRulings(Page.java:175)
	at technology.tabula.extractors.SpreadsheetExtractionAlgorithm.extract(SpreadsheetExtractionAlgorithm.java:86)
	at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:172)
	at technology.tabula.CommandLineApp.main(CommandLineApp.java:60)
`

I have tried limiting the area, but continue to get this error. The PDF did parse fine with tabula-extractor though.

**Comment by nguyentheimo2011** [comment]
Hi, have you figured out how to solve this issue? I have the same problem. I suspect that there is a bug in ObjectExtractor class

**Comment by criztovyl** [comment]
I also have this issue.

Debian Stretch.

    $ java -version
    openjdk version "1.8.0_91"
    OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-2-b14)
    OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by jeremybmerrill** [comment]
I can replicate. Gonna assign to @jazzido, since I don't know a ton about the extractor. (Do you think the float comparison stuff could be doing something funny? Apparently this error is raised when teh sort function is not transitive... )

In the interim, have y'all tried using [tabula-extractor 0.7.6](https://github.com/tabulapdf/tabula-extractor/releases/tag/v0.7.6)? That uses an older version of the extractor and will probably get you similar results.

**Comment by criztovyl** [comment]
I'm using tabula-extractor 0.8.0 and everything works fine.

**Comment by jazzido** [comment]
Replaced `Collections.sort` with our `QuickSort.sort` in [`collapsedOrientedRulings`](https://github.com/tabulapdf/tabula-java/commit/7ce6e3607cc42e9d4eeb64fbe003dbb85495f4b1#diff-68c9509bfb47d99c3538d2ce4c489417R403)

However, there's now an exception in the loop that collapses the sorted lines:

```
java.lang.UnsupportedOperationException
	at technology.tabula.Ruling.getPosition(Ruling.java:64)
	at technology.tabula.Ruling.collapseOrientedRulings(Ruling.java:415)
	at technology.tabula.Ruling.collapseOrientedRulings(Ruling.java:394)
	at technology.tabula.Page.getRulings(Page.java:175)
	at technology.tabula.extractors.SpreadsheetExtractionAlgorithm.extract(SpreadsheetExtractionAlgorithm.java:86)
	at technology.tabula.TestSpreadsheetExtractor.testStableSort(TestSpreadsheetExtractor.java:585)
```
After collapsing a pair of lines into a single one, the latter will have `length == 0`, which will cause an exception in `Ruling.getPosition()`. 

Will keep investigating.

**Comment by criztovyl** [comment]
For me the replace helped, my file now parses(?) successfully. Thank you :)

**Comment by jazzido** [comment]
That's great to hear, @criztovyl!
