### ISSUE TITLE
What is the unit used for --area and --columns options?

### ISSUE THREAD

**Issue by ThomasA** [tabulapdf/tabula-java#84]
I am trying to guess what kind of units are used for the `--area` and `--columns` options. It has been going OK so far with the `--columns` option by trial and error, but just guessing wildly for the `--area` option mostly gets me into this trouble:

    Exception in thread "main" java.util.NoSuchElementException
    	at java.util.ArrayList$Itr.next(ArrayList.java:854)
    	at java.util.Collections.min(Collections.java:635)
    	at technology.tabula.Page.getArea(Page.java:67)
    	at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:145)
    	at technology.tabula.CommandLineApp.main(CommandLineApp.java:60)

**Comment by jazzido** [comment]
Hi @ThomasA,

I guess you resolved the issue by now, but in the benefit of people finding this issue: the units are [PDF Units](https://www.leadtools.com/help/leadtools/v19/dh/to/leadtools.topics.pdf~pdf.topics.pdfcoordinatesystem.html)
