### ISSUE TITLE
Blank CSV file created - OutofBoundsException and unsupported/disabled operation

### ISSUE THREAD

**Issue by sticke4** [tabulapdf/tabula-java#86]
I am having some issues with tabula-java. When I run it on some PDFs, I get the error messages reproduced below. When attempting to output any results to a csv file, the file comes back empty. The files affected work well in the regular Tabula version with the browser based GUI, but I would prefer to use the command line version.

I generated a script from the gui based Tabula so the area coordinates are correct. Unfortunately, I do not fully understand the error messages for me to pinpoint what exactly is going wrong in the affected PDFs. Here is a link to the pdf I have been trying to use [October 2013](http://www.flychicago.com/SiteCollectionDocuments/OHare/AboutUs/NoiseManagement/Aircraft%20Noise%20Management%20System%20Report/2013/2013%20October.pdf) 
and here is the bash script I have been trying with 

```
#!/bin/bash

java -jar tabula-java.jar --no-spreadsheet -a 132.855,29.58,246.84,581.91 -o Test.csv -p 4 2013\ October.pdf

```

Here is the error produced by the program. I have not had luck using the debug switch or routine either.
```
Jun 13, 2016 4:50:44 PM org.apache.pdfbox.util.operator.pagedrawer.FillNonZeroRule process
WARNING: java.lang.ArrayIndexOutOfBoundsException: 40
java.lang.ArrayIndexOutOfBoundsException: 40
        at java.awt.geom.Path2D$Float$TxIterator.currentSegment(Unknown Source)
        at technology.tabula.ObjectExtractor.strokeOrFillPath(ObjectExtractor.java:226)
        at technology.tabula.ObjectExtractor.fillPath(ObjectExtractor.java:285)
        at org.apache.pdfbox.util.operator.pagedrawer.FillNonZeroRule.process(FillNonZeroRule.java:58)
        at org.apache.pdfbox.util.PDFStreamEngine.processOperator(PDFStreamEngine.java:557)
        at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:268)
        at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:235)
        at org.apache.pdfbox.util.PDFStreamEngine.processStream(PDFStreamEngine.java:215)
        at technology.tabula.ObjectExtractor.drawPage(ObjectExtractor.java:153)
        at technology.tabula.ObjectExtractor.extractPage(ObjectExtractor.java:108)
        at technology.tabula.PageIterator.next(PageIterator.java:29)
        at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:142)
        at technology.tabula.CommandLineApp.main(CommandLineApp.java:60)

Jun 13, 2016 4:50:45 PM org.apache.pdfbox.util.PDFStreamEngine processOperator
INFO: unsupported/disabled operation: BDC
Jun 13, 2016 4:50:45 PM org.apache.pdfbox.util.PDFStreamEngine processOperator
INFO: unsupported/disabled operation: i
Jun 13, 2016 4:50:45 PM org.apache.pdfbox.util.PDFStreamEngine processOperator
INFO: unsupported/disabled operation: EMC
Exception in thread "main" java.lang.UnsupportedOperationException
        at technology.tabula.Ruling.getPosition(Ruling.java:64)
        at technology.tabula.Ruling.collapseOrientedRulings(Ruling.java:413)
        at technology.tabula.Ruling.collapseOrientedRulings(Ruling.java:394)
        at technology.tabula.Page.getRulings(Page.java:175)
        at technology.tabula.extractors.SpreadsheetExtractionAlgorithm.extract(SpreadsheetExtractionAlgorithm.java:86)
        at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:172)
        at technology.tabula.CommandLineApp.main(CommandLineApp.java:60)
```

**Comment by sticke4** [comment]
As an update to this post, the problematic pdf file seems to be working with the JRuby implementation of tabula-extractor. Using the same area coordinates I am able to get a csv file with the data.

**Comment by jeremybmerrill** [comment]
This looks PDFBox-related, no? I'm assigning @jazzido , but I worry this may be WONTFIX for now, unless PDFBox provides a point release that fixes this without changing other functionality...

**Comment by alfredino85** [comment]
I have the same problem to extract the table from a pdf, strangely the web app correctly recognize the table but cmd version (with and without area) return me this error:

command 
sudo /var/www/prove_alfredo/tesseract/vendor/oracle-java/jdk1.8.0_92/bin/java -jar /var/www/prove_alfredo/tesseract/vendor/tabula-java/lib/jars/tabula-0.9.0-jar-with-dependencies.jar -g -p all -a 312.14785301208497,36.832702560424806,757.8607587432862,556.2110134124756 -o /var/www/prove_alfredo/tesseract/uploaded_files/cvs0.cvs /var/www/prove_alfredo/tesseract/uploaded_files/HLG-120H-C_DS_001_p1.pdf
result
Exception in thread "main" java.lang.UnsupportedOperationException
        at technology.tabula.Ruling.getPosition(Ruling.java:64)
        at technology.tabula.Ruling.collapseOrientedRulings(Ruling.java:413)
        at technology.tabula.Ruling.collapseOrientedRulings(Ruling.java:394)
        at technology.tabula.Page.getRulings(Page.java:175)
        at technology.tabula.Page.getArea(Page.java:65)
        at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:145)
        at technology.tabula.CommandLineApp.main(CommandLineApp.java:60)

**Comment by sticke4** [comment]
To revisit this, would the problem be PDFBox related if the web app works and the JRuby implementation works but the pure java implementation for the command line doesn't. Don't they all share the same java engine for the extraction?
