### ISSUE TITLE
IllegalArgumentException: shapes can't be empty

### ISSUE THREAD

**Issue by thomasf1** [tabulapdf/tabula-java#87]
i´ve just tried out tabula-java for the fist time.

Cloned it, build it, and run it on a pdf with "java -jar tabula-0.9.0-jar-with-dependencies.jar Rechnung_2016_02_21734396000541.pdf"

Unfortunately, I´m getting the following Exception:

```
Thomass-MacBook-Pro:target tom$ java -jar tabula-0.9.0-jar-with-dependencies.jar Rechnung_2016_02_21734396000541.pdf
Jun 26, 2016 1:15:36 AM org.apache.pdfbox.util.operator.pagedrawer.ClosePath process
WARNING: java.awt.geom.IllegalPathStateException: missing initial moveto in path definition
java.awt.geom.IllegalPathStateException: missing initial moveto in path definition
    at java.awt.geom.Path2D$Float.needRoom(Path2D.java:280)
    at java.awt.geom.Path2D.closePath(Path2D.java:1771)
    at org.apache.pdfbox.util.operator.pagedrawer.ClosePath.process(ClosePath.java:55)
    at org.apache.pdfbox.util.PDFStreamEngine.processOperator(PDFStreamEngine.java:557)
    at org.apache.pdfbox.util.PDFStreamEngine.processOperator(PDFStreamEngine.java:532)
    at org.apache.pdfbox.util.operator.CloseAndStrokePath.process(CloseAndStrokePath.java:44)
    at org.apache.pdfbox.util.PDFStreamEngine.processOperator(PDFStreamEngine.java:557)
    at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:268)
    at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:235)
    at org.apache.pdfbox.util.PDFStreamEngine.processStream(PDFStreamEngine.java:215)
    at technology.tabula.ObjectExtractor.drawPage(ObjectExtractor.java:153)
    at technology.tabula.ObjectExtractor.extractPage(ObjectExtractor.java:108)
    at technology.tabula.PageIterator.next(PageIterator.java:29)
    at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:144)
    at technology.tabula.CommandLineApp.main(CommandLineApp.java:60)

Exception in thread "main" java.lang.IllegalArgumentException: shapes can't be empty
    at technology.tabula.Utils.bounds(Utils.java:44)
    at technology.tabula.extractors.SpreadsheetExtractionAlgorithm.isTabular(SpreadsheetExtractionAlgorithm.java:151)
    at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:152)
    at technology.tabula.CommandLineApp.main(CommandLineApp.java:60)
```

**Comment by semio** [comment]
Same issue here with 0.9.1, but I can extract the PDF with Tabula 1.1 web interface. 

Here is the [link to pdf](https://mics-surveys-prod.s3.amazonaws.com/MICS5/Latin%20America%20and%20Caribbean/Belize/2015-2016/Key%20findings/Belize%202015-16%20MICS%20KFR_English.pdf)

**Comment by jazzido** [comment]
@semio, what arguments triggered the exception? I'd like to check the patch in #104 fixed that issue. Thanks!

**Comment by semio** [comment]
@jazzido This one:

`$ java -jar tabula.jar -p all -o test.csv source.pdf` 

I am running it on OSX and the here is the PDF file [link](https://mics-surveys-prod.s3.amazonaws.com/MICS5/Latin%20America%20and%20Caribbean/Belize/2015-2016/Key%20findings/Belize%202015-16%20MICS%20KFR_English.pdf)

```
$ java -jar tabula.jar -v
tabula 0.9.1 (c) 2012-2016 Manuel Aristarán
```

**Comment by brainopener** [comment]
I am seeing this same issue on Mac OS with latest master (9514e1b3b6b818364e09bbd23832281c24e05a2f).

My command line args are:

`java -jar ./target/tabula-0.9.1-jar-with-dependencies.jar --pages all source.pdf`

**Comment by jeremybmerrill** [comment]
I've replicated the bug by making a selection (in the GUI) on a page with no text at all (anywhere on the page; the bug does not occur with an empty selection on a page that does have text). Fix forthcoming.

**Comment by jeremybmerrill** [comment]
@brainopener @semio: If you get a moment, would you try this patched version to see if the exception no longer occurs? https://www.dropbox.com/s/yekob7tvjuw9l1w/tabula-0.9.1-jar-with-dependencies.jar?dl=0

**Comment by brainopener** [comment]
@jeremybmerrill I do not see the exception with that JAR.

**Comment by jeremybmerrill** [comment]
@brainopener: great, thanks!
